### ISSUE TITLE
Show Version in Backend (Green/Red) including Link to update

### ISSUE THREAD

**Issue by bug-i** [david63/david63-sitelogo#8]
Could you adjust the behaviour of the extension in the backend. Usually alll other extension are indicating if they are up to date or outdated with green/red. 
Thanks!

![grafik](https://user-images.githubusercontent.com/29623218/30643696-386bb60e-9e10-11e7-9401-6f0127190045.png)

**Comment by Galixte** [comment]
Just add this repository to your WatchList to follow this. ;)

**Comment by bug-i** [comment]
ok, done. But thats not that convienent instead of having the overview in the backend :)

**Comment by Galixte** [comment]
I agree, but if david doesn’t want this is an acceptable workaround.

**Comment by bug-i** [comment]
jepp. thats ok for me.
